### ISSUE TITLE
Dropbox Login Page Broken

### ISSUE THREAD

**Issue by trestletech** [Laverna/laverna#351]
When I go to sync with Dropbox, the "Sign In" button never enables. As you can see in the screenshot below, the "Email" and "Password" hints in the text boxes never disappear either. 

![screen shot 2016-01-02 at 7 56 58 pm](https://cloud.githubusercontent.com/assets/1593639/12076967/059cac88-b18b-11e5-80d6-0664b2ce2880.png)

I've tried both without and with my own Dropbox API key and neither works.

Not sure if this is a Dropbox, Electron, or Laverna issue, but I thought I'd start here.

**Comment by wwwredfish** [comment]
Thanks for reporting it. We are working on it.

**Comment by trestletech** [comment]
Thanks for the update.

Do you have any leads on this? I'd be happy to take a stab at fixing it in a PR if so, but I'm new to Electron and am not clear on what the culprit might be here -- especially with out a DevTools window.

I'm excited/motivated to start using the product more heavily, but I don't want to start putting too much content in until I've got a backup solution in place.

**Comment by wwwredfish** [comment]
It seems like @zweicoder has found a solution for the problem in #328 #353. It will be available in the next release soon.

**Comment by varod** [comment]
this seems corrected now in 7.2RC2
tested on linux 64bits

**Comment by trestletech** [comment]
7.2RC2 fixes on OSX. Thanks!

**Comment by Yamakuni** [comment]
Hey!

I use the latest version on MacOs Sierra and have the same problem!

**Comment by flamedmg** [comment]
I'm using arch linux x64 and i still see same thing. I have spare machine with win10x64 - same screen.

**Comment by Krzyrok** [comment]
@Yamakuni @flamedmg 
Download Laverna from the github page - there you can find newer versions. 
I've downloaded 0.7.3 version and this bug is fixed
https://github.com/Laverna/laverna/releases

**Comment by flamedmg** [comment]
@Krzyrok 
Installed fresh version from yaour on arch - now it opens blank windows where it should authenticated with dropbox, waits ~ minute and closes the whole app.

**Comment by Krzyrok** [comment]
On my OS (Windows 10 x64) laverna 0.7.3 works correctly.

**Comment by durandsinclair** [comment]
Got the same problem this morning. The link on the main Laverna page downloads version 0.7.1, so I couldn't authenticate my DropBox account. I downloaded it via the MacOS button at the bottom of this page: https://laverna.cc/index.html

**Comment by BruceZu** [comment]
Got the same problem in Ubuntu 16.04

**Comment by namsohj** [comment]
The problem persist. 

Version: 0.7.1
SO: Mac Capitan

**Comment by slipgatekid** [comment]
Can confirm this is still an issue on Windows 10 Beta v0.7.1

**Comment by slipgatekid** [comment]
Okay, I downloaded .7.4 and this issue seems to be fixed. Its not an official release so I'm not sure what issues there are... Build is from the middle of last year is this software still being developed?

**Comment by ebukari** [comment]
I am having the same problem with v 0.7.51.
I noticed that the bug was fixed in v 0.7.3 and that was before the switch to version 2 of the dropbox API. Has the bug been reintroduced? If then please open this issue  again.

**Comment by funilrys** [comment]
Hi @ebukari @slipgatekid @BruceZu @durandsinclair @Krzyrok @flamedmg @Yamakuni @trestletech @valvin1

Unfortunately this issue will never be fixed here.

Please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the current state of this project and https://github.com/encryptic-team/encryptic for the future of this project.

Have a nice day/night.

Cheers,
Nissar
