### ISSUE TITLE
Image Attachments don't work

### ISSUE THREAD

**Issue by RebelCoderRU** [Laverna/laverna#611]
When image is attached on one platform, from a local Hard-Drive, it is not visible on the other platform.
Attaching the same image, using URL works correctly.

Example images attached.
PC: https://goo.gl/S7eTb1
Android: https://goo.gl/Ep3gHg

**Comment by dlip** [comment]
Same here
Android 0.7.4-RC1
Linux X64 0.7.3

**Comment by varod** [comment]
this is a known "issue" 
related to #358 and #449

**Comment by RebelCoderRU** [comment]
Just wondering if this project is still active. It was left off in a very dry state and has not been updated for a long time :(

**Comment by sprnza** [comment]
Damn it! I've spent half a day to set up a RemoteStorage server and a laverna web app instance to find out that the so called "Evernote replacement" is not able to sync images!! Why this banner is not shown on the main website and github page? It makes the whole idea useless!

**Comment by BennyLi** [comment]
I'm a new Laverna user. It looks very promising and as everyone can see from the commit history it is not dead. Unfortunately I don't understand why there was no release for such a long time.
Anyway, as this bug is really annoying and a show stopper for many users, I would like to contribute.

@wwebfor I've taken a look into the sources. In the RemoteStorage module the files collection is commented out and in the Dropbox module the files collection isn't mentioned anywhere. 

Is there any reason why the files collection wasn't activated for sync? Was there some kind of issues 
I should know about when it was first implemented?

**Comment by KenrySanchez** [comment]
Is this issue fix it? I would like to contribute to the project. i start using laverna and it help me a lot

**Comment by gino909** [comment]
@wwebfor, can you please give us any feedback on this issue?
I guess this is 1 of the most important points in your project! I am willed also to contribute... and I am willed to recommend your solution also to our customers... but in this case the syncronization has to work without any problems given to the fact that our customers working on different devices and need a central cloud storage for his data... and important: for us Dropbox is not a solution given to privacy of data. Remote Storage is ok, because we can create our own server, better would be an webdav integration, with them you open the doors for synching with private cloud storages as owncloud, nextcloud, seafile and many others.
Any feedback from you is really appreciated, thank you

**Comment by wwebfor** [comment]
@gino909, I think it was solved in "dev" branch.

**Comment by gino909** [comment]
Hi
Thank you for your feedback! Do you know when you will release it for public use?

**Comment by 1am** [comment]
Hi. I'm experiencing the same issue using Beta v0.7.51. Tested it in 3 clients (desktop, browser, another browser window in incognito) on the same OSX.

The result is that only the client I used to upload the image shows it but not the others. I even removed the file from my HD after upload and it's still showing up so it didn't cache my local file.
Contents of the notes sync correctly between clients.

I'm using it with encryption enabled, syncing to Dropbox without API key - it's marked as optional but maybe i need it? 

This is my view in desktop app where uploaded the first image (and it's visible): 

![screen shot 2018-11-10 at 14 44 13](https://user-images.githubusercontent.com/959323/48302068-a7ea3800-e4f7-11e8-84a5-af97536817eb.png)

This is my browser view where I uploaded another image (which is visible, but the one from desktop app is not)

![screen shot 2018-11-10 at 14 44 16](https://user-images.githubusercontent.com/959323/48302071-aae52880-e4f7-11e8-8c41-66e626630089.png)

Incognito browser mode where I uploaded no imaged. Both images not showing up:

![screen shot 2018-11-10 at 14 44 30](https://user-images.githubusercontent.com/959323/48302073-ad478280-e4f7-11e8-9e7d-d01457a5a1e6.png)

**Comment by funilrys** [comment]
Hi @RebelCoderRU @dlip @valvin1 @sprnza @BennyLi @KenrySanchez @gino909 @1am 

Unfortunately, this issue will never be fixed here.

Please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the current state of this project and https://github.com/encryptic-team/encryptic for the future of this project.

Have a nice day/night.

Cheers,
Nissar

**Comment by 1am** [comment]
Thanks for the info
