### ISSUE TITLE
Can not log onto Dropbox

### ISSUE THREAD

**Issue by rjdeible-github** [Laverna/laverna#662]
When I try to log onto the Dropbox authorization the login button will not enable, it is disabled.

**Comment by davidmoore-io** [comment]
+1 on this. I'm running Sierra 10.12 with Laverna 0.35.2. 

It's also greying out (rather than hiding) 'Email' and 'Password'

<img width="815" alt="screen shot 2016-11-01 at 02 17 24" src="https://cloud.githubusercontent.com/assets/1043347/19877759/ec583632-9fd9-11e6-958e-09390c8bc6a3.png">

**Comment by jtuyen** [comment]
I'm experiencing the same issue as well when using the Mac OSX client.  The web based version appears to work fine though.

**Comment by notalentgeek** [comment]
I am experiencing this as well. I am on Ubuntu Mate 16.04.

**Comment by G1gas** [comment]
I to am having this issue. Also on Ubuntu Mate 16.04

**Comment by saurabhlambe** [comment]
Facing the same issue on Ubuntu 16.10

**Comment by richard-to** [comment]
I had a similar problem when I download Laverna for Mac from the website. But I had no problems when I downloaded 0.7.3: https://github.com/Laverna/laverna/releases/tag/0.7.3

I think in the  release notes it says the Dropbox authorization bug was resolved

```
This release solves the following bugs:

Dropbox authorization fail #465
Make the app wait until i18next loads a locale
Change load path for i18next locales
```

**Comment by rjdeible-github** [comment]
The release notes may say that but I tried it and it still don't work.

**Comment by mengasis** [comment]
Thank you.
I used version 0.7.3 and the synchronization with dropbox works fine

**Comment by eldelacajita** [comment]
Same issue here on Arch Linux. Tried two versions:

- With latest the version I downloaded from the main page, I got an "unstyled" Dropbox login page with login button disabled. 
- Using the Laverna package from the aur repository (0.7.4), I get a blak green screen with no login information, and the app closes some seconds later.
